site_name: pyPicoSDK

theme:
  name: readthedocs

nav:
  - Home: index.md
  - Reference: 
    - Introduction: ref/introduction.md
    - PicoScope 6000 (A) Specific Functions:
      - ref/ps6000a/init.md
      - ref/ps6000a/setup.md
      - ref/ps6000a/firmware.md
      - ref/ps6000a/channel.md
      - ref/ps6000a/digital.md
      - ref/ps6000a/trigger.md
      - ref/ps6000a/siggen.md
      - ref/ps6000a/buffers.md
      - ref/ps6000a/captures.md
      - ref/ps6000a/run.md
      - ref/ps6000a/retrieval.md
    - General Conversions: ref/conversions.md
    - General Constants: ref/constants.md
  - Development: 
    - Changelog: dev/changelog.md
    - Current Support: dev/current.md
    - Upcoming Roadmap: dev/roadmap.md


plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [..]
        options:
          allow_inspection: true
          docstring_style: google
          show_bases: true
          show_source: false
          inherited_members: true
          members_order: alphabetical
          separate_signature: false
          
extra_css:
- css/mkdocstrings.css